### PR TITLE
Add kli commands and routes mapping table

### PR DESCRIPTION
**Pull request by rubelhassan**
html table syntax is used instead of text format for easy editing of examples later on.

### CODE REVIEW

**Comment by pfeairheller** [comment]
I don't understand the purpose of the table for the `kli`.  The routes listed here apply to any controller using any software to perform different functions and they seem to be repetitive.  For example, the IPEX commands are currently in use in both the command line and KERIA.

**Comment by 2byrds** [comment]
> I don't understand the purpose of the table for the `kli`. The routes listed here apply to any controller using any software to perform different functions and they seem to be repetitive. For example, the IPEX commands are currently in use in both the command line and KERIA.

This is a good question @pfeairheller, but are you questioning if the kli-to-route mapping belongs in this repo (perhaps keripy repo is more appropriate)? Or are you questioning the value of kli-to-route mapping in general? Or something else?

**Comment by SmithSamuelM** [comment]
The confusion may have been caused by me. I was trying to expose everwhere routes were being used so that someone trying to following the functionality of the code from all three API’s (python, Rest, and cli) could connect the dots from the API call to which routes are affected by the api call.  The python and Rest are more direct one-to-one in most cases but the cli is not. But for someone trying to understand what is happening it might still be useful to document.

**Comment by 2byrds** [comment]
> The confusion may have been caused by me. I was trying to expose everwhere routes were being used so that someone trying to following the functionality of the code from all three API’s (python, Rest, and cli) could connect the dots from the API call to which routes are affected by the api call. The python and Rest are more direct one-to-one in most cases but the cli is not. But for someone trying to understand what is happening it might still be useful to document.

I agree that the mapping is very helpful @SmithSamuelM for many reasons; general context, understanding the command-route relationship, understanding the dependency as either evolves, etc. I'm not sure the KAPI repo should be documenting the clients that use it, it seems the reverse is better.... kli documentation in the keripy repo shows this mapping and links back to this KAPI documentation..... however providing 'informative' context like how the kli commands compose the routes to achieve logical functionality is so helpful that I would support it even being here.

**Comment by SmithSamuelM** [comment]
We don't yet have documentation of how the various APIs work. So to me its useful to document the "as built" state of the house before deciding to remodel it.

**Comment by rubelhassan** [comment]
@pfeairheller in addition to @SmithSamuelM's comment, the intentions of this PR are the following: 

1. document routes that involve during an execution of a specific `kli` command
2. incorporates examples of `exn`, `qry` and `rpy` messages that may give insights to the readers.

**Comment by SmithSamuelM** [comment]
@pfeairheller Waiting for your response?

**Review by pfeairheller — APPROVED** [review]
LGTM

**Pull request merged**
